# Dockerfile.test

FROM python:3.9

WORKDIR /app

# Copier les fichiers de dépendances et installer les paquets
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code de l'application et les tests
COPY . /app

# Installer pytest et pytest-mock
RUN pip install pytest pytest-mock

# Commande par défaut pour exécuter les tests
CMD ["pytest", "--maxfail=1", "--disable-warnings", "-q"]
